// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: ef2331b7e2
// Version Date: 2020-10-07T23:22:38Z

package svc

// This file contains methods to make individual endpoints from services,
// request and response types to serve those endpoints, as well as encoders and
// decoders for those types, for all of our supported transport serialization
// formats.

import (
	"context"
	"fmt"

	"github.com/go-kit/kit/endpoint"

	pb "mithril/videosvc"
)

// Endpoints collects all of the endpoints that compose an add service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
//
// In a server, it's useful for functions that need to operate on a per-endpoint
// basis. For example, you might pass an Endpoints to a function that produces
// an http.Handler, with each method (endpoint) wired up to a specific path. (It
// is probably a mistake in design to invoke the Service methods on the
// Endpoints struct in a server.)
//
// In a client, it's useful to collect individually constructed endpoints into a
// single type that implements the Service interface. For example, you might
// construct individual endpoints using transport/http.NewClient, combine them into an Endpoints, and return it to the caller as a Service.
type Endpoints struct {
	PostVideoEndpoint endpoint.Endpoint
	ListVideoEndpoint endpoint.Endpoint
	GetVideoEndpoint  endpoint.Endpoint
}

// Endpoints

func (e Endpoints) PostVideo(ctx context.Context, in *pb.PostRequest) (*pb.PostResponse, error) {
	response, err := e.PostVideoEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.PostResponse), nil
}

func (e Endpoints) ListVideo(ctx context.Context, in *pb.ListRequest) (*pb.ListResponse, error) {
	response, err := e.ListVideoEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.ListResponse), nil
}

func (e Endpoints) GetVideo(ctx context.Context, in *pb.GetVideoRequest) (*pb.GetResponse, error) {
	response, err := e.GetVideoEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.GetResponse), nil
}

// Make Endpoints

func MakePostVideoEndpoint(s pb.VideosServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.PostRequest)
		v, err := s.PostVideo(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeListVideoEndpoint(s pb.VideosServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.ListRequest)
		v, err := s.ListVideo(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeGetVideoEndpoint(s pb.VideosServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.GetVideoRequest)
		v, err := s.GetVideo(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

// WrapAllExcept wraps each Endpoint field of struct Endpoints with a
// go-kit/kit/endpoint.Middleware.
// Use this for applying a set of middlewares to every endpoint in the service.
// Optionally, endpoints can be passed in by name to be excluded from being wrapped.
// WrapAllExcept(middleware, "Status", "Ping")
func (e *Endpoints) WrapAllExcept(middleware endpoint.Middleware, excluded ...string) {
	included := map[string]struct{}{
		"PostVideo": {},
		"ListVideo": {},
		"GetVideo":  {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "PostVideo" {
			e.PostVideoEndpoint = middleware(e.PostVideoEndpoint)
		}
		if inc == "ListVideo" {
			e.ListVideoEndpoint = middleware(e.ListVideoEndpoint)
		}
		if inc == "GetVideo" {
			e.GetVideoEndpoint = middleware(e.GetVideoEndpoint)
		}
	}
}

// LabeledMiddleware will get passed the endpoint name when passed to
// WrapAllLabeledExcept, this can be used to write a generic metrics
// middleware which can send the endpoint name to the metrics collector.
type LabeledMiddleware func(string, endpoint.Endpoint) endpoint.Endpoint

// WrapAllLabeledExcept wraps each Endpoint field of struct Endpoints with a
// LabeledMiddleware, which will receive the name of the endpoint. See
// LabeldMiddleware. See method WrapAllExept for details on excluded
// functionality.
func (e *Endpoints) WrapAllLabeledExcept(middleware func(string, endpoint.Endpoint) endpoint.Endpoint, excluded ...string) {
	included := map[string]struct{}{
		"PostVideo": {},
		"ListVideo": {},
		"GetVideo":  {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "PostVideo" {
			e.PostVideoEndpoint = middleware("PostVideo", e.PostVideoEndpoint)
		}
		if inc == "ListVideo" {
			e.ListVideoEndpoint = middleware("ListVideo", e.ListVideoEndpoint)
		}
		if inc == "GetVideo" {
			e.GetVideoEndpoint = middleware("GetVideo", e.GetVideoEndpoint)
		}
	}
}
